<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>about</title>';
echo '';
echo '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css"/>';
echo '';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">';
echo '';
echo '<link rel="stylesheet" href="css/style.css">';
echo '</head>';
echo '';
echo '<body>';
echo '';
echo '<section class="header">';
echo '';
echo '<a href="home.php" class="logo">travel & tour</a>';
echo '<nav class="navbar">';
echo '<a href="search-page.php">search</a>';
echo '<a href="home.php">home</a>';
echo '<a href="about.php">about</a>';
echo '<a href="places.php">places</a>';
echo '<!--a href="details.php">details</a-->';
echo '</nav>';
echo '';
echo '<div id="menu-btn" class="fas fa-bars"></div>';
echo '';
echo '</section>';
echo '';
echo '<div class="heading" style="background:url(images/heading-img-1.jpg) no-repeat ">';
echo '';
echo '<h1>about us</h1>';
echo '';
echo '</div>';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '<section class="about">';
echo '';
echo '<div class="image">';
echo '<img src="images/about-img.jpg" alt="">';
echo '</div>';
echo '';
echo '<div class="content">';
echo '<h3>why choose us</h3>';
echo '<p>tttttttttttttttttttttttttttttttttt</p>';
echo '<p>qqqqqqqqqqqqqqqqqqqqqqq</p>';
echo '';
echo '<div class="icons-container">';
echo '<div class="icons">';
echo '<i class="fas fa-map"></i>';
echo '<span>top destinations</span>';
echo '</div>';
echo '<div class="icons">';
echo '<i class="fas fa-hand-holding-usd"></i>';
echo '<span>affordable price</span>';
echo '</div>';
echo '<div class="icons">';
echo '<i class="fas fa-headset"></i>';
echo '<span>24/7 open</span>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '</section>';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '<section class="reviews">';
echo '';
echo '<h1 class="heading-title" > clients reviews </h1>';
echo '';
echo '<div class="swiper reviews-slider">';
echo '<div class="swiper-wrapper">';
echo '<div class="swiper-slide slide">';
echo '<div class="stars">';
echo '<i class="fas fa-star"></i>';
echo '<i class="fas fa-star"></i>';
echo '<i class="fas fa-star"></i>';
echo '<i class="fas fa-star"></i>';
echo '<i class="fas fa-star"></i>';
echo '</div>';
echo '<p>is very awesome. i am really liked this.</p>';
echo '<h3>asif</h3>';
echo '<span>traveler</span>';
echo '<img src="images/pic-1.png" width="145" height="145" alt="">';
echo '</div>';
echo '';
echo '<div class="swiper-slide slide">';
echo '<div class="stars">';
echo '<i class="fas fa-star"></i>';
echo '<i class="fas fa-star"></i>';
echo '<i class="fas fa-star"></i>';
echo '<i class="fas fa-star"></i>';
echo '';
echo '</div>';
echo '<p>very nice. and so helpful for traveling.</p>';
echo '<h3>arif</h3>';
echo '<span>traveler</span>';
echo '<img src="images/pic-2.png" width="145" height="145" alt="">';
echo '</div>';
echo '';
echo '<div class="swiper-slide slide">';
echo '<div class="stars">';
echo '<i class="fas fa-star"></i>';
echo '<i class="fas fa-star"></i>';
echo '<i class="fas fa-star"></i>';
echo '';
echo '</div>';
echo '<p>last tour places was awesome and that was really exciting moment for me.</p>';
echo '<h3>soisob</h3>';
echo '<span>traveler</span>';
echo '<img src="images/pic-3.png" width="145" height="145" alt="">';
echo '</div>';
echo '';
echo '<div class="swiper-slide slide">';
echo '<div class="stars">';
echo '<i class="fas fa-star"></i>';
echo '<i class="fas fa-star"></i>';
echo '<i class="fas fa-star"></i>';
echo '<i class="fas fa-star"></i>';
echo '</div>';
echo '<p>very nice. and so helpful for traveling. last tour places was awesome and that was really exciting moment for me.</p>';
echo '<h3>rakin</h3>';
echo '<span>traveler</span>';
echo '<img src="images/pic-4.png" width="145" height="145" alt="">';
echo '</div>';
echo '';
echo '<div class="swiper-slide slide">';
echo '<div class="stars">';
echo '<i class="fas fa-star"></i>';
echo '<i class="fas fa-star"></i>';
echo '<i class="fas fa-star"></i>';
echo '<i class="fas fa-star"></i>';
echo '<i class="fas fa-star"></i>';
echo '</div>';
echo '<p>last tour places was awesome and that was really exciting moment for me. It is very awesome. i am really liked this.</p>';
echo '<h3>selina</h3>';
echo '<span>traveler</span>';
echo '<img src="images/pic-5.png" width="145" height="145" alt="">';
echo '</div>';
echo '';
echo '</div>';
echo '</div>';
echo '</section>';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '<section class="footer">';
echo '';
echo '<div class="box-container">';
echo '';
echo '<div class="box">';
echo '<h3>quick links</h3>';
echo '<a href="home.php"><i class="fas fa-angle-right"></i> home</a>';
echo '<a href="about.php"><i class="fas fa-angle-right"></i>about</a>';
echo '<a href="places.php"><i class="fas fa-angle-right"></i>places</a>';
echo '<!--a href="details.php"><i class="fas fa-angle-right"></i>details</a-->';
echo '</div>';
echo '';
echo '<div class="box">';
echo '<h3>extra links</h3>';
echo '<a href="#"><i class="fas fa-angle-right"></i>ask questions</a>';
echo '<a href="#"><i class="fas fa-angle-right"></i>about us</a>';
echo '<a href="#"><i class="fas fa-angle-right"></i>privacy policy</a>';
echo '<a href="#"><i class="fas fa-angle-right"></i>terms & conditions</a>';
echo '</div>';
echo '';
echo '<div class="box">';
echo '<h3>contact info</h3>';
echo '<a href="#"><i class="fas fa-phone"></i> +8801303654628 </a>';
echo '<a href="#"><i class="fas fa-envelope"></i> asifuzzamanasif001@gmail.com </a>';
echo '<a href="#"><i class="fas fa-map"></i> azimpur </a>';
echo '</div>';
echo '';
echo '<div class="box">';
echo '<h3>follow us</h3>';
echo '<a href="#"><i class="fab fa-facedetails-f"></i> facedetails </a>';
echo '<a href="#"><i class="fab fa-twitter"></i> twitter </a>';
echo '<a href="#"><i class="fab fa-instagram"></i> instagram </a>';
echo '<a href="#"><i class="fab fa-linkedin"></i> linkedin </a>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '<div class="credit">created by <span>team SBD</span>| all rights reserved!</div>';
echo '';
echo '</section>';
echo '';
echo '';
echo '<script src="https://unpkg.com/swiper@7/swiper-bundle.min.js"></script>';
echo '';
echo '<script src="js/script.js"></script>';
echo '';
echo '</body>';
echo '';
echo '';
echo '';
echo '</html>';
?>