<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>book</title>';
echo '';
echo '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css"/>';
echo '';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">';
echo '';
echo '<link rel="stylesheet" href="css/style.css">';
echo '</head>';
echo '';
echo '<body>';
echo '';
echo '<section class="header">';
echo '';
echo '<a href="home.php" class="logo">travel & tour</a>';
echo '<nav class="navbar">';
echo '<a href="home.php">home</a>';
echo '<a href="about.php">about</a>';
echo '<a href="places.php">places</a>';
echo '<a href="book.php">book</a>';
echo '</nav>';
echo '';
echo '<div id="menu-btn" class="fas fa-bars"></div>';
echo '';
echo '</section>';
echo '';
echo '<div class="heading" style="background:url(images/heading-img-3.jpg) no-repeat ">';
echo '';
echo '<h1>book now</h1>';
echo '';
echo '</div>';
echo '';
echo '<section class="booking">';
echo '';
echo '<h1 class="heading-title">book your trip!</h1>';
echo '';
echo '<form action="book_form.php" method="post" class="book-form">';
echo '';
echo '<div class="flex">';
echo '<div class="inputBox">';
echo '<span>name :</span>';
echo '<input type="text" placeholder="enter your name" name="name">';
echo '</div>';
echo '<div class="inputBox">';
echo '<span>email :</span>';
echo '<input type="email" placeholder="enter your email" name="email">';
echo '</div>';
echo '<div class="inputBox">';
echo '<span>phone :</span>';
echo '<input type="number" placeholder="enter your phone number" name="phone">';
echo '</div>';
echo '<div class="inputBox">';
echo '<span>address :</span>';
echo '<input type="text" placeholder="enter your address" name="address">';
echo '</div>';
echo '<div class="inputBox">';
echo '<span>where to :</span>';
echo '<input type="text" placeholder="place you want to visit" name="location">';
echo '</div>';
echo '<div class="inputBox">';
echo '<span>how many :</span>';
echo '<input type="number" placeholder="number of member" name="member">';
echo '</div>';
echo '<div class="inputBox">';
echo '<span>arrivals :</span>';
echo '<input type="date" name="arrivals">';
echo '</div>';
echo '<div class="inputBox">';
echo '<span>leaving :</span>';
echo '<input type="date" name="leaving">';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '<input type="submit" value="submit" class="btn" name="send">';
echo '';
echo '</form>';
echo '';
echo '</section>';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '<section class="footer">';
echo '';
echo '<div class="box-container">';
echo '';
echo '<div class="box">';
echo '<h3>quick links</h3>';
echo '<a href="home.php"><i class="fas fa-angle-right"></i> home</a>';
echo '<a href="about.php"><i class="fas fa-angle-right"></i>about</a>';
echo '<a href="package.php"><i class="fas fa-angle-right"></i>package</a>';
echo '<a href="book.php"><i class="fas fa-angle-right"></i>book</a>';
echo '</div>';
echo '';
echo '<div class="box">';
echo '<h3>extra links</h3>';
echo '<a href="#"><i class="fas fa-angle-right"></i>ask questions</a>';
echo '<a href="#"><i class="fas fa-angle-right"></i>about us</a>';
echo '<a href="#"><i class="fas fa-angle-right"></i>privacy policy</a>';
echo '<a href="#"><i class="fas fa-angle-right"></i>terms & conditions</a>';
echo '</div>';
echo '';
echo '<div class="box">';
echo '<h3>contact info</h3>';
echo '<a href="#"><i class="fas fa-phone"></i> +8801303654628 </a>';
echo '<a href="#"><i class="fas fa-envelope"></i> asifuzzaman01@yahoo.com </a>';
echo '<a href="#"><i class="fas fa-map"></i> azimpur </a>';
echo '</div>';
echo '';
echo '<div class="box">';
echo '<h3>follow us</h3>';
echo '<a href="#"><i class="fab fa-facebook-f"></i> facebook </a>';
echo '<a href="#"><i class="fab fa-twitter"></i> twitter </a>';
echo '<a href="#"><i class="fab fa-instagram"></i> instagram </a>';
echo '<a href="#"><i class="fab fa-linkedin"></i> linkedin </a>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '<div class="credit">created by <span>team SBD</span>| all rights reserved!</div>';
echo '';
echo '</section>';
echo '';
echo '';
echo '<script src="https://unpkg.com/swiper@7/swiper-bundle.min.js"></script>';
echo '';
echo '<script src="js/script.js"></script>';
echo '';
echo '</body>';
echo '';
echo '';
echo '';
echo '</html>';
?>