<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>places</title>';
echo '';
echo '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css"/>';
echo '';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">';
echo '';
echo '<link rel="stylesheet" href="css/style.css">';
echo '</head>';
echo '';
echo '<body>';
echo '';
echo '<section class="header">';
echo '';
echo '<a href="home.php" class="logo">travel & tour</a>';
echo '<nav class="navbar">';
echo '<a href="search-page.php">search</a>';
echo '<a href="home.php">home</a>';
echo '<a href="about.php">about</a>';
echo '<a href="places.php">places</a>';
echo '<!--a href="details/details-1.php">details</a-->';
echo '</nav>';
echo '';
echo '<div id="menu-btn" class="fas fa-bars"></div>';
echo '';
echo '</section>';
echo '';
echo '<div class="heading" style="background:url(images/heading-img-2.jpg) no-repeat ">';
echo '';
echo '<h1>places</h1>';
echo '';
echo '</div>';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '<section class="places">';
echo '';
echo '<h1 class="heading-title">top destinations</h1>';
echo '';
echo '<div class="box-container">';
echo '';
echo '<div class="box">';
echo '<div class="image">';
echo '<img src="images/img-1.jpg" alt="">';
echo '</div>';
echo '<div class="content">';
echo '<h3>lalbagh fort</h3>';
echo '<p>The term Lalbagh refers to reddish and pinkish architecture from the Mughal period. The original fort was called Fort Aurangabad</p>';
echo '<a href="details/details-1.php" class="btn">view more</a>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="box">';
echo '<div class="image">';
echo '<img src="images/img-2.jpg" alt="">';
echo '</div>';
echo '<div class="content">';
echo '<h3>Coxs Bazar</h3>';
echo '<p>fishing port, tourism centre, and district headquarters in Southeastern Bangladesh</p>';
echo '<a href="details/details-2.php" class="btn">view more</a>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="box">';
echo '<div class="image">';
echo '<img src="images/img-3.jpg" alt="">';
echo '</div>';
echo '<div class="content">';
echo '<h3>nilgiri hill</h3>';
echo '<p>Nilgiri or Nil Giri is one of the tallest peaks and beautiful tourist spot in Bangladesh</p>';
echo '<a href="details/details-3.php" class="btn">view more</a>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="box">';
echo '<div class="image">';
echo '<img src="images/img-4.jpg" alt="">';
echo '</div>';
echo '<div class="content">';
echo '<h3>ahsan manzil</h3>';
echo '<p>Ahsan Manzil is a palace located in the Kumartoli area of Dhaka, Bangladesh</p>';
echo '<a href="details/details-4.php" class="btn">view more</a>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="box">';
echo '<div class="image">';
echo '<img src="images/img-5.jpg" alt="">';
echo '</div>';
echo '<div class="content">';
echo '<h3>national martyrs monument</h3>';
echo '<p>National Martyrs Memorial (Jatiya Smriti Saudha) is the national monument of Bangladesh, set up in the memory of those who died in the Bangladesh Liberation War of 1971</p>';
echo '<a href="details/details-5.php" class="btn">view more</a>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="box">';
echo '<div class="image">';
echo '<img src="images/img-6.jpg" alt="">';
echo '</div>';
echo '<div class="content">';
echo '<h3>jaflong</h3>';
echo '<p>Jaflong is a hill station and tourist destination in the Division of Sylhet</p>';
echo '<a href="details/details-6.php" class="btn">view more</a>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="box">';
echo '<div class="image">';
echo '<img src="images/img-7.jpg" alt="">';
echo '</div>';
echo '<div class="content">';
echo '<h3>varendra research museum</h3>';
echo '<p>Varendra Museum is a museum popular visitor attraction at the heart of Rajshahi</p>';
echo '<a href="details/details-7.php" class="btn">view more</a>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="box">';
echo '<div class="image">';
echo '<img src="images/img-8.jpg" alt="">';
echo '</div>';
echo '<div class="content">';
echo '<h3>kuakata sea beach</h3>';
echo '<p>The town Kuakata has sea beach named Kuakata Beach</p>';
echo '<a href="details/details-8.php" class="btn">view more</a>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="box">';
echo '<div class="image">';
echo '<img src="images/img-9.jpg" alt="">';
echo '</div>';
echo '<div class="content">';
echo '<h3>sreemangal</h3>';
echo '<p>Sreemangal is known as the tea capital of Bangladesh</p>';
echo '<a href="details/details-9.php" class="btn">view more</a>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="box">';
echo '<div class="image">';
echo '<img src="images/img-10.jpg" alt="">';
echo '</div>';
echo '<div class="content">';
echo '<h3>saint martin</h3>';
echo '<p>Saint Martin’s, the one and only coral island of Bangladesh</p>';
echo '<a href="details/details-10.php" class="btn">view more</a>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="box">';
echo '<div class="image">';
echo '<img src="images/img-11.jpg" alt="">';
echo '</div>';
echo '<div class="content">';
echo '<h3>panam city</h3>';
echo '<p>Panam shohor/panam nogor) was an ancient city</p>';
echo '<a href="details/details-11.php" class="btn">view more</a>';
echo '</div>';
echo '</div>';
echo '';
echo '<div class="box">';
echo '<div class="image">';
echo '<img src="images/img-12.jpg" alt="">';
echo '</div>';
echo '<div class="content">';
echo '<h3>sundarban</h3>';
echo '<p>Sundarban Reserve Forest of Bangladesh is the largest mangrove forest in the world</p>';
echo '<a href="details/details-12.php" class="btn">view more</a>';
echo '</div>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '<div class="load-more"> <a class="btn">load more</a></div>';
echo '<!--div class="load-more"> <a href="places.php" class="btn">load more</a></div-->';
echo '';
echo '</section>';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '<section class="footer">';
echo '';
echo '<div class="box-container">';
echo '';
echo '<div class="box">';
echo '<h3>quick links</h3>';
echo '<a href="home.php"><i class="fas fa-angle-right"></i> home</a>';
echo '<a href="about.php"><i class="fas fa-angle-right"></i>about</a>';
echo '<a href="places.php"><i class="fas fa-angle-right"></i>places</a>';
echo '<!--a href="details.php"><i class="fas fa-angle-right"></i>details</a-->';
echo '</div>';
echo '';
echo '<div class="box">';
echo '<h3>extra links</h3>';
echo '<a href="#"><i class="fas fa-angle-right"></i>ask questions</a>';
echo '<a href="#"><i class="fas fa-angle-right"></i>about us</a>';
echo '<a href="#"><i class="fas fa-angle-right"></i>privacy policy</a>';
echo '<a href="#"><i class="fas fa-angle-right"></i>terms & conditions</a>';
echo '</div>';
echo '';
echo '<div class="box">';
echo '<h3>contact info</h3>';
echo '<a href="#"><i class="fas fa-phone"></i> +8801303654628 </a>';
echo '<a href="#"><i class="fas fa-envelope"></i> asifuzzaman01@yahoo.com</a>';
echo '<a href="#"><i class="fas fa-map"></i> azimpur </a>';
echo '</div>';
echo '';
echo '<div class="box">';
echo '<h3>follow us</h3>';
echo '<a href="#"><i class="fab fa-facedetails-f"></i> facedetails </a>';
echo '<a href="#"><i class="fab fa-twitter"></i> twitter </a>';
echo '<a href="#"><i class="fab fa-instagram"></i> instagram </a>';
echo '<a href="#"><i class="fab fa-linkedin"></i> linkedin </a>';
echo '</div>';
echo '';
echo '</div>';
echo '';
echo '<div class="credit">created by <span>team SBD</span>| all rights reserved!</div>';
echo '';
echo '</section>';
echo '';
echo '';
echo '<script src="https://unpkg.com/swiper@7/swiper-bundle.min.js"></script>';
echo '';
echo '<script src="js/script.js"></script>';
echo '';
echo '</body>';
echo '';
echo '';
echo '';
echo '</html>';
?>