<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css"/>';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">';
echo '<link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/thinline.css">';
echo '<script src="https://kit.fontawesome.com/a076d05399.js"></script>';
echo '<style>';
echo '.search-input .icon{';
echo 'height: 55px;';
echo 'width: 55px;';
echo 'line-height: 55px;';
echo 'position: absolute;';
echo 'top: 0;';
echo 'right: 0;';
echo 'text-align: center;';
echo 'font-size: 20px;';
echo 'color: #4070f4;';
echo 'cursor: pointer;';
echo '}';
echo 'body {';
echo 'font-family: Arial, sans-serif;';
echo 'margin: 0;';
echo 'padding: 0;';
echo 'background-color: #f0f0f0;';
echo '}';
echo '.container {';
echo 'max-width: 1200px;';
echo 'margin: 0 auto;';
echo 'padding: 20px;';
echo '}';
echo '.header {';
echo 'display: flex;';
echo 'align-items: center;';
echo 'justify-content: space-between;';
echo 'padding: 20px;';
echo 'background-color: #f0f0f0;';
echo '}';
echo '.logo {';
echo 'height: 50px;';
echo '}';
echo '.nav {';
echo 'list-style: none;';
echo 'display: flex;';
echo 'margin-right: -10px;';
echo '}';
echo '.nav li {';
echo 'margin-left: 10px;';
echo '}';
echo '.nav a {';
echo 'text-decoration: none;';
echo 'color: #333;';
echo 'padding: 10px;';
echo 'border-radius: 10px;';
echo '}';
echo '.nav a:hover {';
echo 'background-color: #ddd;';
echo 'color: white;';
echo '}';
echo '';
echo '.gcse-search {';
echo 'margin-top: 20px;';
echo '}';
echo '.search {';
echo 'position: relative;';
echo 'margin-top: 40px;';
echo '}';
echo '.search input {';
echo 'width: 100%;';
echo 'height: 40px;';
echo 'border: none;';
echo 'border-bottom: 2px solid #333;';
echo 'outline: none;';
echo 'font-size: 20px;';
echo 'padding-left: 10px;';
echo '}';
echo '.search button {';
echo 'position: absolute;';
echo 'right: 0;';
echo 'top: 0;';
echo 'height: 40px;';
echo 'width: 40px;';
echo 'border: none;';
echo 'background-color: transparent;';
echo 'cursor: pointer;';
echo '}';
echo '.search button img {';
echo 'height: 20px;';
echo '}';
echo '.categories {';
echo 'display:flex;';
echo 'margin-top :20px;';
echo 'flex-wrap: wrap;';
echo 'gap: 20px;';
echo '}';
echo '.categories.active {';
echo 'display :grid;';
echo 'grid-template-columns: repeat(8,1fr);';
echo 'gap :10px;';
echo '}';
echo '.category {';
echo 'height :100px;';
echo 'width: 200px;';
echo 'border-radius: 10px;';
echo 'background-size : cover;';
echo 'background-position: center;';
echo 'display: flex;';
echo 'position: relative;';
echo 'align-items: center;';
echo 'justify-content: center;';
echo 'cursor: pointer;';
echo 'box-shadow: inset -2px rgba(255,255,255,0.1),';
echo 'inset -1px -1px rgba(255,255,255,.1),';
echo 'inset -3px -3px rgba(255,255,255,.1),';
echo 'inset -4px -4px rgba(255,255,255,.1),';
echo 'inset -5px -5px rgba(255,255,255,.1),';
echo 'inset -6px -6px rgba(255,255,255,.1),';
echo 'inset -7px -7px rgba(255,255,255,.1),';
echo 'inset -8px -8px rgba(255,255,255,.1),';
echo 'inset -9px -9px rgba(255,255,255,.1),';
echo 'inset -10px -10px rgba(255,255,255,.1),';
echo 'inset -11px -11px rgba(255,255,255,.1),';
echo 'inset -12px -12px rgba(255,255,255,.1),';
echo 'inset -13px -13px rgba(255,255,255,.1),';
echo 'inset -14px -14px rgba(255,255,255,.1);';
echo '}';
echo '.category h3 {';
echo 'color: white;';
echo 'font-size :16px;';
echo 'margin: 0;';
echo 'padding: 10px;';
echo 'position: absolute;';
echo 'bottom: 0;';
echo 'left: 0;';
echo 'right: 0;';
echo 'background-color: rgba(0,0,0,0.5);';
echo '';
echo '}';
echo '';
echo '.category:hover h3 {';
echo 'background-color: rgba(0,0,0,0.8);';
echo '}';
echo '</style>';
echo '</head>';
echo '<body>';
echo '<div class="container">';
echo '<div class="header">';
echo '<img src="images/logo.png" alt="Logo" class="logo">';
echo '<ul class="nav">';
echo '<li><a href="home.php">Home</a></li>';
echo '<li><a href="about.php">About</a></li>';
echo '<li><a href="places.php">Places</a></li>';
echo '</ul>';
echo '</div>';
// echo '<script async src="https://cse.google.com/cse.js?cx=f14b12872b17b48c0"> </script>';

echo '<section class="search__bar">';
    echo '<form class="container search__bar-container" action="<?= ROOT_URL ?>search-logic.php" method="GET">';
        echo '<div>';
           echo ' <i class="uil uil-search"></i>';
           echo ' <input type="search" name="search" placeholder="Search">';
        echo '</div>';
       echo ' <button type="submit" name="submit" class="btn">Go</button>';
    echo '</form>';
echo '</section>';


echo '<div class="gcse-search">';
echo '';
echo '</div>';

echo '<script>';
echo '';
echo 'var searchInput = document.getElementById("search-input");';
echo 'var searchButton = document.getElementById("search-button");';
echo 'var categories = document.getElementById("categories");';
echo 'var categoryLinks = document.querySelectorAll(".category a");';
echo 'var categoryNames = [];';
echo 'for (var i = 0; i < categoryLinks.length; i++) {';
echo 'var categoryName = categoryLinks[i].querySelector("h3").textContent;';
echo 'categoryNames.push(categoryName);';
echo '}';
echo 'searchButton.addEventListener("click", function() {';
echo 'var query = searchInput.value.toLowerCase();';
echo 'if (query) {';
echo 'categories.classList.add("active");';
echo 'for (var i = 0; i < categoryNames.length; i++) {';
echo 'var categoryName = categoryNames[i].toLowerCase();';
echo 'if (categoryName.includes(query)) {';
echo 'categoryLinks[i].style.display = "block";';
echo '} else {';
echo 'categoryLinks[i].style.display = "none";';
echo '}';
echo '}';
echo '} else {';
echo 'categories.classList.remove("active");';
echo '}';
echo '});';
echo '</script>';

echo '';
echo '<div id="categories" class="categories">';
echo '';
echo '<a href="details/dhaka.php">';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Dhaka_District.png/250px-Dhaka_District.png)">';
echo '<h3>Dhaka</h3>';
echo '</div>';
echo '</a>';
echo '<a href="https://wikiofinfo.com/faridpur-tourist-places/">';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Faridpur_District.png/250px-Faridpur_District.png)">';
echo '<h3>Faridpur</h3>';
echo '</div>';
echo '</a>';
echo '<a href="https://wikiofinfo.com/gazipur-tourist-places/">';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Gazipur_District.png/250px-Gazipur_District.png)">';
echo '<h3>Gazipur</h3>';
echo '</div>';
echo '</a>';
echo '<a href="https://wikiofinfo.com/gopalganj-tourist-places/">';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Gopalganj_District.png/250px-Gopalganj_District.png)">';
echo '<h3>Gopalganj</h3>';
echo '</div>';
echo '</a>';
echo '<a href="https://wikiofinfo.com/jamalpur-tourist-places/">';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Jamalpur_District.png/250px-Jamalpur_District.png)">';
echo '<h3>Jamalpur</h3>';
echo '</div>';
echo '</a>';
echo '<a href="https://wikiofinfo.com/kishoreganj-tourist-places/">';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Kishoreganj_District.png/250px-Kishoreganj_District.png)">';
echo '<h3>Kishoreganj</h3>';
echo '</div>';
echo '</a>';
echo '<a href="https://wikiofinfo.com/madaripur-tourist-places/">';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Madaripur_District.png/250px-Madaripur_District.png)">';
echo '<h3>Madaripur</h3>';
echo '</div>';
echo '</a>';
echo '<a href="https://wikiofinfo.com/manikganj-tourist-places/">';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Manikganj_District.png/250px-Manikganj_District.png)">';
echo '<h3>Manikganj</h3>';
echo '</div>';
echo '</a>';
echo '<a href="https://wikiofinfo.com/munshiganj-tourist-places/">';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Munshiganj_District.png/250px-Munshiganj_District.png)">';
echo '<h3>Munshiganj</h3>';
echo '</div>';
echo '</a>';
echo '<a href="https://wikiofinfo.com/mymensingh-tourist-places/">';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Mymensingh_District.png/250px-Mymensingh_District.png)">';
echo '<h3>Mymensingh</h3>';
echo '</div>';
echo '</a>';
echo '<a href="https://wikiofinfo.com/narayanganj-tourist-places/">';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Narayanganj_District.png/250px-Narayanganj_District.png)">';
echo '<h3>Narayanganj</h3>';
echo '</div>';
echo '</a>';
echo '<a href="https://wikiofinfo.com/narsingdi-tourist-places/">';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Narsingdi_District.png/250px-Narsingdi_District.png)">';
echo '<h3>Narsingdi</h3>';
echo '</div>';
echo '</a>';
echo '<a href="https://wikiofinfo.com/netrokona-tourist-places/">';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Netrokona_District.png/250px-Netrokona_District.png)">';
echo '<h3>Netrokona</h3>';
echo '</div>';
echo '</a>';
echo '';
echo '';
echo '<a href="https://wikiofinfo.com/bandarban-tourist-places-in-bangladesh/#Bandarban_Tourist_Places_in_Bangladesh">';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Bandarban_district.svg/1200px-Bandarban_district.svg.png)">';
echo '<h3>Bandarban</h3>';
echo '</div>';
echo '</a>';
echo '';
echo '';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Brahmanbaria_district.svg/1200px-Brahmanbaria_district.svg.png)">';
echo '<h3>Brahmanbaria</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Chandpur_district.svg/1200px-Chandpur_district.svg.png)">';
echo '<h3>Chandpur</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Chattogram_district.svg/1200px-Chattogram_district.svg.png)">';
echo '<h3>Chattogram</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Cumilla_district.svg/1200px-Cumilla_district.svg.png)">';
echo '<h3>Cumilla</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Cox%27s_Bazar_district.svg/1200px-Cox%27s_Bazar_district.svg.png)">';
echo '<h3>Coxs Bazar</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Feni_district.svg/1200px-Feni_district.svg.png)">';
echo '<h3>Feni</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Khagrachhari_district.svg/1200px-Khagrachhari_district.svg.png)">';
echo '<h3>Khagrachhari</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Lakshmipur_district.svg/1200px-Lakshmipur_district.svg.png)">';
echo '<h3>Lakshmipur</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Noakhali_district.svg/1200px-Noakhali_district.svg.png)">';
echo '<h3>Noakhali</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Rangamati_district.svg/1200px-Rangamati_district.svg.png)">';
echo '<h3>Rangamati</h3>';
echo '</div>';
echo '';
echo '';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Habiganj_District.png/250px-Habiganj_District.png)">';
echo '<h3>Habiganj</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Maulvibazar_District.png/250px-Maulvibazar_District.png)">';
echo '<h3>Maulvibazar</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Sunamganj_District.png/250px-Sunamganj_District.png)">';
echo '<h3>Sunamganj</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Sylhet_District.png/250px-Sylhet_District.png)">';
echo '<h3>Sylhet</h3>';
echo '</div>';
echo '';
echo '';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Barguna_District.png/250px-Barguna_District.png)">';
echo '<h3>Barguna</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Bhola_District.png/250px-Bhola_District.png)">';
echo '<h3>Bhola</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Jhalokati_District.png/250px-Jhalokati_District.png)">';
echo '<h3>Jhalokati</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Patuakhali_District.png/250px-Patuakhali_District.png)">';
echo '<h3>Patuakhali</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Pirojpur_District.png/250px-Pirojpur_District.png)">';
echo '<h3>Pirojpur</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Barishal_District.png/250px-Barishal_District.png)">';
echo '<h3>Barishal</h3>';
echo '</div>';
echo '';
echo '';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Bagerhat_District.png/250px-Bagerhat_District.png)">';
echo '<h3>Bagerhat</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Chuadanga_District.png/250px-Chuadanga_District.png)">';
echo '<h3>Chuadanga</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Jessore_District.png/250px-Jessore_District.png)">';
echo '<h3>Jashore</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Jhenaidah_District.png/250px-Jhenaidah_District.png)">';
echo '<h3>Jhenaidah</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Khulna_District.png/250px-Khulna_District.png)">';
echo '<h3>Khulna</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Kushtia_District.png/250px-Kushtia_District.png)">';
echo '<h3>Kushtia</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Magura_District.png/250px-Magura_District.png)">';
echo '<h3>Magura</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Meherpur_District.png/250px-Meherpur_District.png)">';
echo '<h3>Meherpur</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Narail_District.png/250px-Narail_District.png)">';
echo '<h3>Narail</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/e/e4/Satkhira_District.png/250px-Satkhira_District.png)">';
echo '<h3>Satkhira</h3>';
echo '</div>';
echo '';
echo '';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Bogura_district.svg/1200px-Bogura_district.svg.png)">';
echo '<h3>Bogura</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Joypurhat_district.svg/1200px-Joypurhat_district.svg.png)">';
echo '<h3>Joypurhat</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/a/a6/Natore_district.svg/1200px-Natore_district.svg.png)">';
echo '<h3>Natore</h3>';
echo '</div>';
echo '';
echo '';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Nawabganj_district.svg/1200px-Nawabganj_district.svg.png)">';
echo '<h3>Nawabganj</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Pabna_district.svg/1200px-Pabna_district.svg.png)">';
echo '<h3>Pabna</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Rajshahi_district.svg/1200px-Rajshahi_district.svg.png)">';
echo '<h3>Rajshahi</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/Sirajganj_district.svg/1200px-Sirajganj_district.svg.png)">';
echo '<h3>Sirajganj</h3>';
echo '</div>';
echo '';
echo '';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Dinajpur_district.svg/1200px-Dinajpur_district.svg.png)">';
echo '<h3>Dinajpur</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Gaibandha_district.svg/1200px-Gaibandha_district.svg.png)">';
echo '<h3>Gaibandha</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Kurigram_district.svg/1200px-Kurigram_district.svg.png)">';
echo '<h3>Kurigram</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Lalmonirhat_district.svg/1200px-Lalmonirhat_district.svg.png)">';
echo '<h3>Lalmonirhat</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Nilphamari_district.svg/1200px-Nilphamari_district.svg.png)">';
echo '<h3>Nilphamari</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Panchagarh_district.svg/1200px-Panchagarh_district.svg.png)">';
echo '<h3>Panchagarh</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Rangpur_District.png/250px-Rangpur_District.png)">';
echo '<h3>Rangpur</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Thakurgaon_District.png/250px-Thakurgaon_District.png)">';
echo '<h3>Thakurgaon</h3>';
echo '</div>';
echo '';
echo '';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Jamalpur_District.png/250px-Jamalpur_District.png)">';
echo '<h3>Jamalpur</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/a/a2/Mymensingh_District.png/250px-Mymensingh_District.png)">';
echo '<h3>Mymensingh</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Netrokona_District.png/250px-Netrokona_District.png)">';
echo '<h3>Netrokona</h3>';
echo '</div>';
echo '<div class="category" style="background-image:url(https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Sherpur_District.png/250px-Sherpur_District.png)">';
echo '<h3>Sherpur</h3>';
echo '</div>';
echo '';
echo '</div>';
echo '</body>';
echo '';
echo '<script>';
echo 'var searchInput = document.getElementById("search-input");';
echo 'var searchButton = document.getElementById("search-button");';
echo 'var categories = document.getElementById("categories");';
echo 'var categoryLinks = document.querySelectorAll(".category a");';
echo '';
echo 'var categoryNames = [];';
echo 'for (var i = 0; i < categoryLinks.length; i++)';
echo '{';
echo 'var categoryName = categoryLinks[i].querySelector("h3").textContent;';
echo '';
echo 'categoryNames.push(categoryName);';
echo '}';
echo '';
echo 'searchButton.addEventListener("click", function() {';
echo 'var query = searchInput.value.toLowerCase();';
echo '';
echo 'if (query) { categories.classList.add("active");';
echo '';
echo 'for (var i = 0; i < categoryNames.length; i++)';
echo '{ var categoryName = categoryNames[i].toLowerCase();';
echo '';
echo 'if (categoryName.includes(query)) {';
echo 'categoryLinks[i].style.display = "block";';
echo '';
echo '}';
echo 'else {';
echo 'categoryLinks[i].style.display = "none";';
echo '';
echo '}';
echo '}';
echo '}';
echo 'else {';
echo 'categories.classList.remove("active");';
echo '';
echo '}';
echo '});';
echo '</script>';
echo '';
echo '</html>';
echo '';
echo '';
echo '';
?>