<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>Place details</title>';
echo '';
echo '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css"/>';
echo '';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">';
echo '';
echo '<link rel="stylesheet" href="css/style.css">';
echo '';
echo '</head>';
echo '<body>';
echo '<section class="header">';
echo '';
echo '<a href="home.php" class="logo">travel & tour</a>';
echo '<nav class="navbar">';
echo '<a href="search.php">search</a>';
echo '<a href="home.php">home</a>';
echo '<a href="about.php">about</a>';
echo '<a href="places.php">places</a>';
echo '<!--a href="details.php">book</a-->';
echo '</nav>';
echo '';
echo '<div id="menu-btn" class="fas fa-bars"></div>';
echo '';
echo '</section>';
echo '';
echo '<div class="heading">';
echo '';
echo '<h1 style= "color: black;" >Kuakata</h1>';
echo '';
echo '</div>';
echo '';
echo '';
echo '';
echo '<iframe align="right" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d118830.24483338387!2d91.93268932172899!3d21.451043284590487!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x30adc7ea2ab928c3%3A0x3b539e0a68970810!2sCox&#39;s%20Bazar!5e0!3m2!1sen!2sbd!4v1679482709170!5m2!1sen!2sbd" width="600" height="450" style="border: 1px solid black; border-radius: 10px;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>';
echo '';
echo '<div class="content">';
echo '<p align="left" style="font-size: 20px;">Kuakata beach is a sandy expanse 18 kilometres (11 mi) long and 3 kilometres (1.9 mi) wide. From the beach one can have an unobstructed view of both sunrise and sunset over the Bay of Bengal.</p>';
echo '<h3>How to go?</h3>';
echo '<p align="left" style="font-size: 20px;">Kuakata sea beach is located in the Patuakhali district of Bangladesh1. Here are some ways to get there:';
echo '';
echo 'By bus: You can take a bus from Dhaka to Kuakata. The journey takes around 10-12 hours2.';
echo 'By car: You can also drive from Dhaka to Kuakata. The distance between the two cities is around 320 km1.';
echo 'By plane: You can take a flight from Dhaka to Barisal and then take a bus or car to Kuakata</p>';
echo '';
echo '<a href="/book.php" class="btn">Tour now</a>';
echo '</div>';
echo '';
echo '</body>';
echo '</html>';
?>