<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>Place details</title>';
echo '';
echo '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css"/>';
echo '';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">';
echo '';
echo '<link rel="stylesheet" href="css/style.css">';
echo '';
echo '</head>';
echo '<body>';
echo '<section class="header">';
echo '';
echo '<a href="home.php" class="logo">travel & tour</a>';
echo '<nav class="navbar">';
echo '<a href="search.php">search</a>';
echo '<a href="home.php">home</a>';
echo '<a href="about.php">about</a>';
echo '<a href="places.php">places</a>';
echo '<!--a href="details.php">book</a-->';
echo '</nav>';
echo '';
echo '<div id="menu-btn" class="fas fa-bars"></div>';
echo '';
echo '</section>';
echo '';
echo '<div class="heading">';
echo '';
echo '<h1 style= "color: black;" >Nilgiri</h1>';
echo '';
echo '</div>';
echo '';
echo '';
echo '';
echo '<iframe align="right" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d5233.444528683271!2d92.30907102323269!3d21.949765671618973!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x30ad79f269ee1ca1%3A0xe20af8c3ae6b3cb!2sBandarban%20-%20Thanchi%20Rd!5e0!3m2!1sen!2sbd!4v1679595406644!5m2!1sen!2sbd" width="600" height="450" style="border: 1px solid black; border-radius: 10px;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>';
echo '';
echo '<div class="content">';
echo '<p align="left" style="font-size: 20px;"></p>';
echo '<h3>How to go?</h3>';
echo '<p align="left" style="font-size: 20px;">If you want to go to Nilgiri from any part of the country, you have to come to Bandarban first. From Bandarban to Nilgiri, you can go by Jeep, Chander Gari, Mahendra, CNG, or by local bus. The best way is to get a reserve car. It will help you to explore some of the surrounding areas of Nilgiri and Bandarban. If you want to come back within the day, you have to pick up the car from Bandarban Jeep Station. According to different cars, it may cost you BDT 3000 to 5000. In a Chander Gari, you may go 12 – 14 people, with the Landcruizer type jeep, you may go 7 to 8 people, with the Small jeep you may go to 4 to 5 people and with CNG you may go 2 to 3 persons. On the way to Nilgiri, due to security concerns, the name and addresses of the tourists need to be recorded on the army checkpoint. For this reason, there is no other way or not allowed to go to Nilgiri after 5 PM. So keep the eye on the time before travel. For traveling to the Nilgiri, as a tourist, you will need tickets with BDT 50 per person and BDT 300 for parking the car.</p>';
echo '';
echo '<a href="/book.php" class="btn">Tour now</a>';
echo '</div>';
echo '';
echo '</body>';
echo '</html>';
?>