<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>Place details</title>';
echo '';
echo '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css"/>';
echo '';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">';
echo '';
echo '<link rel="stylesheet" href="css/style.css">';
echo '';
echo '</head>';
echo '<body>';
echo '<section class="header">';
echo '';
echo '<a href="home.php" class="logo">travel & tour</a>';
echo '<nav class="navbar">';
echo '<a href="search.php">search</a>';
echo '<a href="home.php">home</a>';
echo '<a href="about.php">about</a>';
echo '<a href="places.php">places</a>';
echo '<!--a href="details.php">book</a-->';
echo '</nav>';
echo '';
echo '<div id="menu-btn" class="fas fa-bars"></div>';
echo '';
echo '</section>';
echo '';
echo '<div class="heading">';
echo '';
echo '<h1 style= "color: black;" >Cox*s Bazar</h1>';
echo '';
echo '</div>';
echo '';
echo '';
echo '';
echo '<iframe align="right" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d118830.24483338387!2d91.93268932172899!3d21.451043284590487!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x30adc7ea2ab928c3%3A0x3b539e0a68970810!2sCox&#39;s%20Bazar!5e0!3m2!1sen!2sbd!4v1679482709170!5m2!1sen!2sbd" width="600" height="450" style="border: 1px solid black; border-radius: 10px;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>';
echo '';
echo '<div class="content">';
echo '<p align="left" style="font-size: 20px;"></p>';
echo '<h3>How to go?</h3>';
echo '<p align="left" style="font-size: 20px;">Located about 150 km south of Chittagong Metropolitan city, Coxs Bazar is connected both by air and road with the capital of Bangladesh, Dhaka and the prime port city Chittagong. Daily non-stop flights are available from Chittagong and Dhaka on United Airways or Regent. The journey by plane takes 60 minutes and the fare is BD taka.6000.00 and 3500.00 one way from Dhaka & Chittagong respectievly. By bus it will take about 10-12 hours from Dhaka and 4-5 hours from Chittagong. The private AC Bus line named "Greenline", "Soudia", "Hanif","TR Travels" "Shamoli" and "Amader Baghdad" are available from Dhaka and Chittagong. AC bus will take BDT 1400-1800 from Dhaka to Coxs"bazar. Moreover, many non-AC services are also available from Dhaka and Chittagong costing from BD taka.350.00-750.00(from Dhaka) or BD taka 500.00-560.00 (from Chittagong). The main bus terminal is a few kilometers east of the central town area, about a 15-20 minute  Tk 100-120 by electric bike known as "Easy Bike" or CNG auto ride. Local buses head to Chittagong (Tk 120, 4 hours) and Teknaf (Tk 70, 3 hours). The private bus companies have offices near "Hotel Sea Queen" on the main road, and also down in the hotel-motel zone. During the tourist season bus tickets goes scarcity requires advance ticketing to avoid delayed staying. Better to book immediately on arrival</p>';
echo '<a href="/book.php" class="btn">Tour now</a>';
echo '</div>';
echo '';
echo '</body>';
echo '</html>';
?>