<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>Place details</title>';
echo '';
echo '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css"/>';
echo '';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">';
echo '';
echo '<link rel="stylesheet" href="css/style.css">';
echo '';
echo '</head>';
echo '<body>';
echo '<section class="header">';
echo '';
echo '<a href="home.php" class="logo">travel & tour</a>';
echo '<nav class="navbar">';
echo '<a href="search.php">search</a>';
echo '<a href="home.php">home</a>';
echo '<a href="about.php">about</a>';
echo '<a href="places.php">places</a>';
echo '<!--a href="details.php">book</a-->';
echo '</nav>';
echo '';
echo '<div id="menu-btn" class="fas fa-bars"></div>';
echo '';
echo '</section>';
echo '';
echo '<div class="heading">';
echo '';
echo '<h1 style= "color: black;" >Saint Martin’s</h1>';
echo '';
echo '</div>';
echo '';
echo '';
echo '';
echo '<iframe align="right" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3823745.4953615074!2d90.0821838625!3d20.623701600000004!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x30ae23666ddf01b1%3A0xfb9c82c83dacf078!2sSaint%20Martins%20Island!5e0!3m2!1sen!2sbd!4v1679602123856!5m2!1sen!2sbd" width="600" height="450" style="border: 1px solid black; border-radius: 10px;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>';
echo '';
echo '<div class="content">';
echo '<p align="left" style="font-size: 20px;">Saint Martin’s, the one and only coral island of Bangladesh, is a small island measuring eight square kilometers. The visible landmass sinks during the tide. Alternatively called the pearl of the sea, it is about 10 km from the mainland at teknaf.</p>';
echo '<h3>How to go?</h3>';
echo '<p align="left" style="font-size: 20px;">Saint Martin Island is located in the Bay of Bengal and is accessible only by water transportation1. Here are some ways to get there:';
echo '';
echo 'By ferry: You can take a ferry from Teknaf to Saint Martin Island. The journey takes around 2 hours and costs around $30 USD2.';
echo 'By boat: You can also take a boat from Cox Bazar to Saint Martin Island</p>';
echo '';
echo '<a href="/book.php" class="btn">Tour now</a>';
echo '</div>';
echo '';
echo '</body>';
echo '</html>';
?>