<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>Place details</title>';
echo '';
echo '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css"/>';
echo '';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">';
echo '';
echo '<link rel="stylesheet" href="css/style.css">';
echo '';
echo '</head>';
echo '<body>';
echo '<section class="header">';
echo '';
echo '<a href="/home.php" class="logo">travel & tour</a>';
echo '<nav class="navbar">';
echo '<a href="/search.php">search</a>';
echo '<a href="/home.php">home</a>';
echo '<a href="/about.php">about</a>';
echo '<a href="/places.php">places</a>';
echo '<a href="/book.php">places</a>';
echo '<!--a href="details.php">book</a-->';
echo '</nav>';
echo '';
echo '<div id="menu-btn" class="fas fa-bars"></div>';
echo '';
echo '</section>';
echo '';
echo '<div class="heading">';
echo '';
echo '<h1 style= "color: black;" >Lalbagh Fort</h1>';
echo '';
echo '</div>';
echo '';
echo '';
echo '';
echo '<iframe align="right" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3652.799153083125!2d90.38596554997712!3d23.718865395822885!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3755b8d900000001%3A0x4e16316ffc66e862!2z4Kay4Ka-4Kay4Kas4Ka-4KaXIOCmleCnh-CmsuCnjeCmsuCmvg!5e0!3m2!1sen!2sbd!4v1679481990977!5m2!1sen!2sbd" width="600" height="450" style="border: 1px solid black; border-radius: 10px;"  allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>';
echo '';
echo '<div class="content">';
echo '';
echo '<p align="left" style="font-size: 20px;">Lalbagh Fort is one of the key tourist attractions of Dhaka City in Bangladesh. This is an unfinished Mughal fort from the 17th century, the constructions of which was started by a mughal prince who was the governor of Dhaka at that time. But when he left, the construction was not finished by the next governor in charge because of a family tragedy. Nevertheless, the forts massive size and the structures inside bring many local tourists to the fort every day. Located in the lalbagh area in old Dhaka and hence achieving its name, it is the most popular and renowned fort and a great art signature by the mughal empire in Bangladesh. It is also known as fort Aurangabad. It is situated by the bank of the river Buriganga in rich red soil. For anyone visiting bangladesh, lalbagh fort is one of the must-visiting attractions.</p>';
echo '<h3>How to go?</h3>';
echo '<p align="left" style="font-size: 20px;">Lalbagh fort is located in the old town of dhaka, he capital city of Bangladesh. Old Dhaka is the part of Dhaka where the city was originally founded by the Mughals in the 17th-century as the capital of eastern Bengle. The fort is located in Dhaka beside the river buriganga, which flows a little further in the present days. the co-ordinate of Lalbagh fort is 23.7189, 90.3882. You can view the location of lalbagh fort on this map.</p>';
echo '';
echo '<a href="/book.php" class="btn">Tour now</a>';
echo '</div>';
echo '';
echo '</body>';
echo '</html>';
?>