<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>Place details</title>';
echo '';
echo '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css"/>';
echo '';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">';
echo '';
echo '<link rel="stylesheet" href="css/style.css">';
echo '';
echo '</head>';
echo '<body>';
echo '<section class="header">';
echo '';
echo '<a href="home.php" class="logo">travel & tour</a>';
echo '<nav class="navbar">';
echo '<a href="search.php">search</a>';
echo '<a href="home.php">home</a>';
echo '<a href="about.php">about</a>';
echo '<a href="places.php">places</a>';
echo '<!--a href="details.php">book</a-->';
echo '</nav>';
echo '';
echo '<div id="menu-btn" class="fas fa-bars"></div>';
echo '';
echo '</section>';
echo '';
echo '<div class="heading">';
echo '';
echo '<h1 style= "color: black;" >Varendra Museum</h1>';
echo '';
echo '</div>';
echo '';
echo '';
echo '';
echo '<iframe align="right" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1817.2034695970335!2d88.59143726675806!3d24.36714318556986!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39fbef06fc9f05fb%3A0xa24b2e60bfa403be!2sVarendra%20Research%20Museum!5e0!3m2!1sen!2sbd!4v1679481681813!5m2!1sen!2sbd" width="800" height="600" style="border: 1px solid black; border-radius: 10px;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>';
echo '';
echo '<div class="content">';
echo '<p align="left" style="font-size: 20px;">Varendra Museum (Bengali: বরেন্দ্র জাদুঘর) is a museum, research centre, and popular visitor attraction at the heart of Rajshahi and maintained by Rajshahi University in Bangladesh. It is considered the oldest museum in Bangladesh. It was the first museum to be established in East Bengal in 1910. The museum started out as the collection for Varendra Anushandan Samiti (or Varendra Investigation Society) and got its current name in 1919</p>';
echo '<h3>How to go?</h3>';
echo '<p align="left" style="font-size: 20px;">Here are some ways to get there:';
echo '';
echo 'By train: The best way to go to Varendra Research Museum from Dhaka is by train. The train departs from Dhaka’s Kamalapur Railway Station and arrives at Rajshahi Railway Station. From Rajshahi Railway Station, you can take a rickshaw or a bus to the Varendra Research Museum1.';
echo 'By bus: You can also go to Varendra Research Museum by bus. From Rajshahi Bus Terminal, you can take a rickshaw or a bus to the museum1.';
echo 'By car: If you are traveling by car, it will take you around 2 hours to reach Varendra Research Museum from Dhaka. The distance between the two cities is around 150 kilometers</p>';
echo '';
echo '<a href="/book.php" class="btn">Tour now</a>';
echo '</div>';
echo '';
echo '</body>';
echo '</html>';
?>