<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>Place details</title>';
echo '';
echo '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css"/>';
echo '';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">';
echo '';
echo '<link rel="stylesheet" href="css/style.css">';
echo '';
echo '</head>';
echo '<body>';
echo '<section class="header">';
echo '';
echo '<a href="home.php" class="logo">travel & tour</a>';
echo '<nav class="navbar">';
echo '<a href="search.php">search</a>';
echo '<a href="home.php">home</a>';
echo '<a href="about.php">about</a>';
echo '<a href="places.php">places</a>';
echo '<!--a href="details.php">book</a-->';
echo '</nav>';
echo '';
echo '<div id="menu-btn" class="fas fa-bars"></div>';
echo '';
echo '</section>';
echo '';
echo '<div class="heading">';
echo '';
echo '<h1 style= "color: black;" >Ahsan Manzil</h1>';
echo '';
echo '</div>';
echo '';
echo '<iframe align="right" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3653.0881373127704!2d90.40603279999999!3d23.708546400000003!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3755b9047a855555%3A0xdb6be1e307885b57!2sAhsan%20Manzil%20Museum!5e0!3m2!1sen!2sbd!4v1679595558055!5m2!1sen!2sbd" width="600" height="450" style="border: 1px solid black; border-radius: 10px;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>';
echo '';
echo '<div class="content">';
echo '<p align="left" style="font-size: 20px;">Ahsan Manzil is a palace located in the Kumartoli area of Dhaka, Bangladesh. It was formerly the residence and seat of the Nawab of Dhaka and has been designated an Old Dhaka Heritage Site. The construction of Ahsan Manzil was started by Nawab Abdul Ghani in 1859 and completed in 1872. He named it after his son Khwaja Ahsanullah (1846–1901)12. It has been turned into a museum that showcases the history of the palace and its inhabitants</p>';
echo '<h3>How to go?</h3>';
echo '<p align="left" style="font-size: 20px;">You can visit Ahsan Manzil from anywhere in Dhaka. You can take a local bus to Sadar Ghat and from there you can take a small rickshaw ride straight to the gate of Ahsan Manzil. It is also suggested to take a rickshaw or walk through the old town.</p>';
echo '';
echo '<a href="/book.php" class="btn">Tour now</a>';
echo '</div>';
echo '';
echo '</body>';
echo '</html>';
?>