<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>Place details</title>';
echo '';
echo '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css"/>';
echo '';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">';
echo '';
echo '<link rel="stylesheet" href="css/style.css">';
echo '';
echo '</head>';
echo '<body>';
echo '<section class="header">';
echo '';
echo '<a href="home.php" class="logo">travel & tour</a>';
echo '<nav class="navbar">';
echo '<a href="search.php">search</a>';
echo '<a href="home.php">home</a>';
echo '<a href="about.php">about</a>';
echo '<a href="places.php">places</a>';
echo '<!--a href="details.php">book</a-->';
echo '</nav>';
echo '';
echo '<div id="menu-btn" class="fas fa-bars"></div>';
echo '';
echo '</section>';
echo '';
echo '<div class="heading">';
echo '';
echo '<h1 style= "color: black;" >Sundarban</h1>';
echo '';
echo '</div>';
echo '';
echo '';
echo '';
echo '<iframe align="right" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d787843.7752149879!2d89.2869768!3d22.0190853!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3a004caac2c7b315%3A0x4716abcfbb16c93c!2sSundarbans!5e1!3m2!1sen!2sbd!4v1679602978274!5m2!1sen!2sbd" width="600" height="450" style="border: 1px solid black; border-radius: 10px;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>';
echo '';
echo '<div class="content">';
echo '<p align="left" style="font-size: 20px;">The Sundarbans, one of the most attractive places in Bangladesh, is the largest mangrove forest in the world. Visitors feel great enthusiasm and fascination to come to this nature’s bounties of exceptional character. The forest is a World Heritage Site for its extra-ordinary vegetation and diverse ecological balance.</p>';
echo '<h3>How to go?</h3>';
echo '<p align="left" style="font-size: 20px;">Sundarban is located in the southern part of Bangladesh and is accessible by air, road or steamer1. The easiest way to reach Sundarban is by steamer from Khulna which is the gateway to Sundarban12. You can also take a motor vessel from Mongla to Hiron Point or Katka3. Prior permission must be obtained through written application from the Divisional Forest Office, Circuit House Road, Khulna to visit the Sundarbans3. The required entrance fees for visitors, vessel or boat are payable at the relevant forest station/range office.</p>';
echo '';
echo '<a href="/book.php" class="btn">Tour now</a>';
echo '</div>';
echo '';
echo '</body>';
echo '</html>';
?>