<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>Place details</title>';
echo '';
echo '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css"/>';
echo '';
echo '<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css">';
echo '';
echo '<link rel="stylesheet" href="css/style.css">';
echo '';
echo '</head>';
echo '<body>';
echo '<section class="header">';
echo '';
echo '<a href="/home.php" class="logo">travel & tour</a>';
echo '<nav class="navbar">';
echo '<a href="/search.php">search</a>';
echo '<a href="/home.php">home</a>';
echo '<a href="/about.php">about</a>';
echo '<a href="/places.php">places</a>';
echo '<a href="/book.php">places</a>';
echo '<!--a href="details.php">book</a-->';
echo '</nav>';
echo '';
echo '<div id="menu-btn" class="fas fa-bars"></div>';
echo '';
echo '</section>';
echo '';
echo '<div class="heading">';
echo '';
echo '<h1 style= "color: black;" >Dhaka</h1>';
echo '';
echo '</div>';
echo '';
echo '';
echo '';
echo '<iframe align="right" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d467323.8105381909!2d89.9286062888655!3d23.784179822675778!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3755bf587b89f1c7%3A0xb19ded8dd11f042f!2sDhaka%20District!5e0!3m2!1sen!2sbd!4v1686203897996!5m2!1sen!2sbd" width="600" height="450" style="border: 1px solid black; border-radius: 10px;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>';
echo '';
echo '<div class="content">';
echo '';
echo '<div>';
echo '<h3>Lalbagh Fort</h3>';
echo '<img src="images/img-1.jpg" alt="" height="200px" width="300px" style="border: 1px solid black; border-radius: 10px;">';
echo '<a href="details-1.php" class="btn">See More</a>';
echo '</div>';
echo '';
echo '<div>';
echo '<h3>Ahsan Manjil</h3>';
echo '<img src="images/img-4.jpg" alt="" height="200px" width="300px" style="border: 1px solid black; border-radius: 10px;">';
echo '<a href="details-4.php" class="btn">See More</a>';
echo '</div>';
echo '';
echo '<div>';
echo '<h3>Karjonhall</h3>';
echo '<a href="details-1.php" class="btn">See More</a>';
echo '</div>';
echo '';
echo '';
echo '';
echo '';
echo '';
echo '</div>';
echo '';
echo '</body>';
echo '</html>';
?>